services:
  php:
    build:
      context: .
      target: prod
      dockerfile: frankenphp/dockerfile
    restart: always
  
  database:
    restart: always
  
  cache:
    restart: always
  
  gotenberg:
    restart: always
