services:
  php:
    build:
      context: .
      target: frankenphp_prod
      dockerfile: frankenphp/Dockerfile
    labels:
      caddy: "ttcastelnovien.com"
      caddy.reverse_proxy: "{{upstreams 8000}}"
    networks:
      - reverse_proxy
      - net_database
      - net_cache
      - net_gotenberg
    restart: always
    volumes:
      - "$PWD/secrets:/app/secrets"
      - vol_caddy_data:/data
      - vol_caddy_config:/config
  
  database:
    restart: always
  
  cache:
    restart: always
  
  gotenberg:
    restart: always

networks:
  reverse_proxy:
    external: true
